### ISSUE TITLE
Il logo va cambiato anche nella Console

### ISSUE THREAD

**Issue by ilgrosso** [FeanorAmarth/MvnSyncopePrjct#1]
Nelle specifiche dell'esercizio c'era scritto:

> Sostituire il logo standard di Syncope con [1], sia nella Admin Console sia nell'Enduser UI

Ho verificato che la sostituzione è stata correttamente eseguita nell'Enduser, ma non nella Console.

**Comment by FeanorAmarth** [comment]
Ne sono cosciente ed ho cercato di risolvere questo punto ma, se non ho capito male, la documentazione di riferimento dice che: è sufficiente inserire nel progetto il path "img/logo.png", perciò ho generato nella cartella console l'albero "console/src/main/webapp/app/img" che contiene sia logo.png che logo-green.png tuttavia non sembra prendere la personalizzazione. Probabilmente mi sfugge qualcosa.

**Comment by FeanorAmarth** [comment]
sono riuscito a risolvere accorgendomi dell'errore nel percorso delle directory, anche se mi renodo conto che al momento la mia soluzione è abbastanza brutale.
