### ISSUE TITLE
Rimuovere ext/swagger-ui

### ISSUE THREAD

**Issue by ilgrosso** [FeanorAmarth/MvnSyncopePrjct#2]
E' semplicemente un clone del modulo corrispondente su Syncope, e non è incluso nella compilazione - rimuoverlo.

**Comment by FeanorAmarth** [comment]
Mi scuso per la svista, è un residuo del processo di risoluzione (non ancora terminato) del bug che affligge l'endpoint REST. Ho rimosso.
